import matplotlib.pyplot as plt
import pandas as pd

# Read the data from the CSV file generated by the Bash script
data = pd.read_csv("data.csv", header=None)
data.columns = ['Total Requests', 'GET Requests', 'POST Requests', 'Failures', 'Failure Percent']

# Convert to numeric types
total_requests = int(data['Total Requests'].iloc[0])
get_requests = int(data['GET Requests'].iloc[0])
post_requests = int(data['POST Requests'].iloc[0])
failures = int(data['Failures'].iloc[0])
failure_percent = float(data['Failure Percent'].iloc[0])

# Request Types (GET vs POST) Graph
plt.figure(figsize=(8, 6))
plt.bar(['GET', 'POST'], [get_requests, post_requests], color=['blue', 'orange'])
plt.title('GET vs POST Requests')
plt.xlabel('Request Type')
plt.ylabel('Count')
plt.legend(['GET Requests (Blue)', 'POST Requests (Orange)'])
plt.tight_layout()
plt.savefig('get_vs_post_requests.png')
plt.show()

# Failure Rate (Failures vs Success) Graph (Pie chart)
failure_labels = ['Successful Requests', 'Failed Requests']
failure_values = [total_requests - failures, failures]
plt.figure(figsize=(8, 6))
plt.pie(failure_values, labels=failure_labels, autopct='%1.1f%%', colors=['lightgreen', 'salmon'], startangle=90)
plt.title(f'Failure Rate: {failure_percent:.2f}% Failed Requests')
plt.legend(['Successful Requests (Light Green)', 'Failed Requests (Salmon)'])
plt.tight_layout()
plt.savefig('failure_rate.png')
plt.show()

# Requests by Hour Graph (Bar chart)
requests_by_hour = {
    "00": 150, "01": 120, "02": 100, "03": 80, "04": 90, "05": 110,
    "06": 180, "07": 210, "08": 250, "09": 300, "10": 270, "11": 230,
    "12": 240, "13": 220, "14": 190, "15": 180, "16": 170, "17": 160,
    "18": 210, "19": 200, "20": 220, "21": 250, "22": 230, "23": 190
}

# Convert dictionary to lists for plotting
hours = list(requests_by_hour.keys())
requests = list(requests_by_hour.values())

plt.figure(figsize=(10, 6))
plt.bar(hours, requests, color='skyblue')
plt.title('Requests by Hour')
plt.xlabel('Hour of the Day')
plt.ylabel('Requests Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.legend(['Hourly Requests (Sky Blue)'])
plt.savefig('requests_by_hour.png')
plt.show()

# Status Code Breakdown (Pie chart)
status_code = {
    "200": 4500,
    "404": 300,
    "500": 100
}
status_labels = list(status_code.keys())
status_counts = list(status_code.values())

plt.figure(figsize=(8, 6))
plt.pie(status_counts, labels=status_labels, autopct='%1.1f%%', colors=['gold', 'lightcoral', 'lightgray'], startangle=90)
plt.title('Status Code Breakdown')
plt.legend(['200 OK (Gold)', '404 Not Found (Light Coral)', '500 Internal Server Error (Light Gray)'])
plt.tight_layout()
plt.savefig('status_code_breakdown.png')
plt.show()
